/**
 * This class is generated by jOOQ
 */
package com.github.akovari.rdfp.data.schema.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.case_links_id_seq</code>
	 */
	public static final Sequence<Long> CASE_LINKS_ID_SEQ = new SequenceImpl<Long>("case_links_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
