/**
 * This class is generated by jOOQ
 */
package com.github.akovari.rdfp.data.schema.public_;


import com.github.akovari.rdfp.data.schema.public_.tables.CaseLinks;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.case_links
	 */
	public static final CaseLinks CASE_LINKS = com.github.akovari.rdfp.data.schema.public_.tables.CaseLinks.CASE_LINKS;
}
