/**
 * This class is generated by jOOQ
 */
package com.github.akovari.rdfp.data.schema.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "case_links", schema = "public")
public class CaseLinks implements Serializable {

	private static final long serialVersionUID = -342302737;

	private final Integer id;
	private final String  url;
	private final String  caseId;

	public CaseLinks(CaseLinks value) {
		this.id = value.id;
		this.url = value.url;
		this.caseId = value.caseId;
	}

	public CaseLinks(
		Integer id,
		String  url,
		String  caseId
	) {
		this.id = id;
		this.url = url;
		this.caseId = caseId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 32)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	@Column(name = "case_id", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getCaseId() {
		return this.caseId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CaseLinks (");

		sb.append(id);
		sb.append(", ").append(url);
		sb.append(", ").append(caseId);

		sb.append(")");
		return sb.toString();
	}
}
